on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    container:
      image: archlinux:base
      volumes:
        - .:/code
    steps:
      - name: Hello world action step
        id: hello
        uses: yfblock/qemu-9-docker-actions@main
      - name: Run code in a docker container
        run: pacman -Syy qemu-system-loongarch64
      - run: qemu-system-loongarch64 --version
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

